### ISSUE TITLE
Broken link to event payloads

### ISSUE THREAD

**Issue by hpurmann** [getsentry/develop#18]
On the [SDK development overview page](https://develop.sentry.dev/sdk/store/), there is a paragraph saying:

> For a list of all supported attributes and interfaces in event payloads, see [Event Payloads](https://develop.sentry.dev/sdk/event-payloads/).

Unfortunately, the link is broken at the moment.

I managed to find https://github.com/getsentry/develop/blob/master/src/docs/sdk/event-payloads/overview.mdx in the meantime :)

**Comment by dcramer** [comment]
Had a quick convo in Slack about this since they were moved to the top level.

I'm going to add a third tier to docs links and make it easier to generate navigation (e.g. an `<AutoNavLinks>` component. Then we'll likely throw Event Payloads back under /sdk/ and I can cleanup the bad links in parallel.

Right now you'll find them down in the sidebar:

https://develop.sentry.dev/sdk/event-payloads/overview/
