### ISSUE TITLE
Document default values for 'Span.op' on auto instrumented SDKs

### ISSUE THREAD

**Issue by marandaneto** [getsentry/develop#247]
`http.server` for HTTP servers
`http.client` for HTTP clients

Context: #242
Also https://github.com/getsentry/sentry-java/pull/1165#discussion_r560295316

Python does `http` for HTTP clients
https://github.com/getsentry/sentry-python/blob/ca828c9486f4a0030a744849a4e8e10c5a1c7aeb/sentry_sdk/integrations/stdlib.py#L81

as only `http` alone is ambiguous, I'd prefer to be more specific.

Let's fix this on Python (and what else?) and write it down on the docs?

**Comment by marandaneto** [comment]
cc @untitaker @rhcarvalho @bruno-garcia

**Comment by untitaker** [comment]
sgtm

**Comment by bruno-garcia** [comment]
At first I thought it was related to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md but turns out it's just our on `op` for Spans.

Makes sense to align like you suggested. That means we're changing python though @untitaker? To have `http.server` and `http.client` ?

**Comment by rhcarvalho** [comment]
Yes, AFAICT the names were based on old versions of the semantic conventions (same for span statuses).

I'm good with `http.server` and `http.client`, don't see a problem with changing this for all SDKs. AFAIK the Sentry UI does not relay on specific names.

**Comment by ahmedetefy** [comment]
Sounds good! Opened up a ticket for it https://app.asana.com/0/1159797622087522/1200117075062458

**Comment by marandaneto** [comment]
https://develop.sentry.dev/sdk/performance/span-operations/
