### ISSUE TITLE
Define behavior of overriding transaction on the scope

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/develop#297]
We're exploring APIs that will automatically bind a new transaction to the scope.

So instead of the current documented:

```
var tran = Sentry.startTransaction('a');
Sentry.configureScope(s -> s.transaction = tran);
```

It becomes:
```
// Already binds to scope:
var tran = Sentry.startTransaction('a');

// Or to skip binding it to the scope:
var tran = Sentry.startTransaction('a', bindToScope: false);
```

Calling `tran.finish()` results in a call to an internal API such as `Sentry.resetTransaction(this)` which will compare the reference bound to the scope, and if it's still the same, it'll remove itself. Atomically.

Questions:

1. Does this make sense?
2. Should the default be: bind to scope: `true`?
2. What happens when there's already something bound to the scope? 
  * Don't override? 
    * User will expect to have that transaction propagated but that won't be the case.
  * Finish the old transaction with context: _Superseded by TransactionXYZ_
    * This will help troubleshoot things though our automatic transactions can be causing this and "breaking" user-defined transaction. 
  * Override it and don't mess with the old transaction? 
    * Likely means it'll just be GC'ed and all data would be lost.

**Comment by rhcarvalho** [comment]
> We're exploring APIs that will automatically bind a new transaction to the scope.

What problem are you trying to solve?

---

We might be conflating two behaviors/questions here:

1. What happens when setting a transaction on the scope when a different transaction was already there?
2. Should starting a transaction automatically set it on the current scope?

Both questions have come up before, and saying "yes" to the second question begs for a satisfactory answer for the first.

As far as memory serves me, we've considered automatically setting transactions to the current scope when they are started, but have multiple times eventually concluded that that was not worth the consequences, in the form of the subsequent questions posed in the issue description.

I'd also add that it seems confusing that `StartTransaction` would maybe finish another transaction depending on global state. Typically transactions/spans are finished by the `finish` method, the exceptions being context managers in Python and the automatic transactions provided by SDKs (frontend pageload, backend request, etc).

---

Perhaps what we should be looking into is whether the scope is the best abstraction to manage spans in the first place. Goes back to "what problem are we trying to solve?"

**Comment by marandaneto** [comment]
@rhcarvalho Mobile SDKs are single/global Hub, hence a single Scope too.

The problem is: Transactions are created automatically by auto instrumentation, so if people are doing eg a HTTP request, this HTTP request that is happening in a different thread should find the transaction to create a child span out of it and where to find? Scope.

Now let's say that my screen has 2 use cases and I want 2 parallel transactions, auto instrumentation created one, the user has created the 2nd one, which one lives in the Scope? who created first or what?

Let's say now that we have a List of transactions within the Scope, again, a HTTP request happens, from which transaction should we create our span, the 1st or 2nd? and here we go down to the can of worms

**Comment by rhcarvalho** [comment]
@marandaneto fair question. The "wanting to report HTTP request spans" is a problem that surfaces in browser frontend too, and we're discussing solutions to that.

For the time being, isn't it possible to use `PushScope` to run the two transactions in different scopes?

**Comment by marandaneto** [comment]
@rhcarvalho no

> Mobile SDKs are single/global Hub, hence a single Scope too

**Comment by bruno-garcia** [comment]
Binding the transaction upon creation is a new API/behavioir and after talking to @mitsuhiko we decided not to bring this into the spec or add to any new SDK. That's until we do a bigger pass on where we are and where we want to be in terms of performance API.

Regarding the current spec. the current behavior if someone overrides a transaction via `configureScope(s -> s.transction` is still undefined though: Do we close the overriding transaction so it's captured? Do we just let it get GC'ed?

**Comment by rhcarvalho** [comment]
> the current behavior if someone overrides a transaction via `configureScope(s -> s.transction` is still undefined

The behavior is the same as overriding any field in the scope, it replaces the previous value without any side-effect.

From the scope alone it is not possible to determine the fate of the "old" transaction. It may be eventually finished using another reference to the value, or if there are no more references it may be GC'ed. (Would be interested to see how this works in Rust, probably it won't compile if you just leak a transaction).
