### ISSUE TITLE
Proposal: Response interface (analogous to the Request interface)

### ISSUE THREAD

**Issue by ueman** [getsentry/develop#401]
It would be nice if an event has a `response` interface, just like the [`request`](https://develop.sentry.dev/sdk/event-payloads/request/) interface.

An application makes a request and gets a response. This response can lead to crashes, by having data with which the application cannot work. Just knowing the `request` isn't as helpful as having the `response` as well. 

This is especially useful for integrations like https://github.com/getsentry/sentry-dart/pull/473 where HTTP requests can be captured as an exception if the status code is considered "bad". Example: Imaging you want to catch every status code from 400 to 499 as an exception and send it to Sentry. The responses from 400 to 499 often include hints on what's wrong with the request (wrong combination of parameter or whatnot). This information is lost because responses aren't recorded.
This in turn makes this kind of events hard to fix.

Having responses can be useful in non server applications such as mobile or desktop apps, but also for micro-services and servers which communicate via HTTP.

cc @bruno-garcia and @marandaneto because they wanted to hear my insights and learnings from https://github.com/getsentry/sentry-dart/pull/473

**Comment by marandaneto** [comment]
it has been a topic already, I'll discuss it internally, thanks.

**Comment by marandaneto** [comment]
the idea is that we add a new `type=http` in the Contexts interface -> https://develop.sentry.dev/sdk/event-payloads/contexts/

the data structure could be the same as the Request interface https://develop.sentry.dev/sdk/event-payloads/request/

the UI should render nicely as it does for the Request interface

using the Contexts for the http type allows having multiple names eg request, response, etc... since a service might do a request to different services etc.

**Comment by ueman** [comment]
What if I want to have a request and a response?

**Comment by marandaneto** [comment]
thats not a problem, similar to https://develop.sentry.dev/sdk/event-payloads/contexts/#example and type=os

**Comment by marandaneto** [comment]
https://github.com/getsentry/rfcs/blob/main/text/0022-response-context.md
Its going to be implemented.
