### ISSUE TITLE
Add Dynamic Sampling Context + Baggage Spec

### ISSUE THREAD

**Issue by smeubank** [getsentry/develop#611]
In Develop Docs

Write down baggage propagation “spec” to define clear rules of how baggage is created and passed along downstream. 

clarify confusion around naming:
- trace context vs baggage
- "propagation mechanism"
- content - what is in it?
  - call it dynamic sampling context
  - meaning: the key values included in the baggage header

The following list is probably not complete but it should include (writing this down after the meeting on Daily from 18th):
- Check if incoming request has baggage header and parse it to see if there’s sentry- entries in it
- If not, create the baggage content (i.e. the sentry- keys) and propagate it with the outgoing requests
  - include the specific contect types (release, environment, user, transaction, usergroup)
- If yes, leave it untouched (don’t add/change stuff) and send it along with the outgoing request  
- In any of those two cases, “foreign” baggage entries must be passed along with the next outgoing requests (if they exist)

reference existing docs

https://github.com/getsentry/develop/issues/425

https://github.com/getsentry/develop/issues/409

**Comment by antonpirker** [comment]
A list of PRs that @Lms24 sent me with all the baggage functionality in JS. Maybe this helps writing the documentation?

1. Baggage data structures and operations
	* https://github.com/getsentry/sentry-javascript/pull/5066

1. Baggage data in Envelope Header
	* https://github.com/getsentry/sentry-javascript/pull/5104
	* https://github.com/getsentry/sentry-javascript/pull/5128
	* (Mutability of Baggage only handled in 5)

1. Baggage passing on to outgoing requests (without data population)
	* https://github.com/getsentry/sentry-javascript/pull/5133

1. Release and Environment propagation
	* https://github.com/getsentry/sentry-javascript/pull/5193

1. Mutability of Baggage:
	* https://github.com/getsentry/sentry-javascript/pull/5205
	* https://github.com/getsentry/sentry-javascript/pull/5218

**Comment by smeubank** [comment]
https://github.com/getsentry/sentry-javascript/issues/5290#issuecomment-1161734110

for reference of what concerns to address see this comment. Notes from SDK DS sync. Transactions have platform specific complexities. Maybe a table where devs can include descriptions and examples of such can be included

**Comment by smeubank** [comment]
confirming list of relevant values:

Trace-aware head sampling based on trace state information from the frontend SDK (requires SDK support):

- Transaction name
- Release
- Environment
- User ID
- User Segment
- No condition - uniform sampling rate

@ale-cota can you clarify what "No condition" means?

**Comment by Lms24** [comment]
@smeubank to add on the list posted above:

@lforst and I talked about names/keys of values to be propagated via baggage and sent via an envelope header. He'll include a detailed list once his PR is ready but this is what we came up with:

**Baggage keys**:
* `sentry-traceid`
* `sentry-publickey`
* `sentry-samplerate`
* `sentry-environment`
* `sentry-release`
* `sentry-transaction`
* `sentry-userid`
* `sentry-usersegment`

**Envelope header items**
Envelope header items (for `trace` header) are described in [Develop docs](https://develop.sentry.dev/sdk/performance/trace-context/#trace-context) as well as implemented in [Relay](https://github.com/getsentry/relay/blob/master/relay-sampling/src/lib.rs#L685-L707). 
Additionally, in Relay a field must be added for the sample rate, which we propose to call
* `sample_rate` (for consistency with other fields)

**Comment by AbhiPrasad** [comment]
As part of these docs, I would like to take some time to establish the terms we refer to these different concepts.

Traces, transactions, and spans have all been long defined in [our product docs](https://docs.sentry.io/product/sentry-basics/tracing/distributed-tracing/#traces-transactions-and-spans).

In event payload (so both errors and transactions), there exists the [contexts interface](https://develop.sentry.dev/sdk/event-payloads/contexts/), one of which is the [Trace Contexts](https://develop.sentry.dev/sdk/event-payloads/transaction/#contextstrace) (a contexts keyed by `trace`). I believe this should continue to be referred to as such.

We then have the key-value bag needed to make dynamic sampling decisions. Previously this was called [Trace Contexts also](https://develop.sentry.dev/sdk/performance/trace-context/#trace-context), but I propose it be called **Dynamic Sampling Context** (thanks @lobsterkatie for the suggestion). This dynamic sampling context is used in two ways:

1) It is sent to Sentry through the envelope header, keyed by `trace`.

2) It is propogated between services (and so between different Sentry SDKs running in those services) so that dynamic sampling can occur on entire traces. Currently the mechanism for propogation we have chosen for the SDKs is leveraging the baggage HTTP header, based on the [w3c baggage spec](https://www.w3.org/TR/baggage/).

**Comment by mitsuhiko** [comment]
I like the idea of calling this dynamic sampling context, so that gets a buy-in from me. Annoyingly on the relay side the `TraceContext` and the dynamic sampling context are in fact synonyms right now I believe. I think that in the protocol it's in fact currently the case that the `trace` item in the envelope headers have exactly the same format as the trace context in the protocol but someone from relay would need to double check that.

**Comment by jjbayer** [comment]
@mitsuhiko In relay, these are two different structs with the same name. As far as I can see, `trace_id` is the only overlap:
https://github.com/getsentry/relay/blob/d217da6fdf3392f0476a0b019223e267c7c90df0/relay-sampling/src/lib.rs#L687
https://github.com/getsentry/relay/blob/d217da6fdf3392f0476a0b019223e267c7c90df0/relay-general/src/protocol/contexts.rs#L475
